### ISSUE TITLE
🕳️ Add Underground Variant Blocks

### ISSUE THREAD

**Issue by jonathan-robertson** [jonathan-robertson/gmo-farming#1]
GMO Crafting by merging existing seeds with Mushroom seeds, Underground Plant Variants can grow with zero sunlight.

## Tasks
- [x] Generate Blocks
- [x] Generate Recipes
- [x] Generate Localization/Names

## Additions in `blocks.xml`
- Duplicate each block and stage with roughly this approach
```xml
<append xpath="/blocks">
  <block name="plantedUndergroundAloe1">
    <property name="Extends" value="plantedAloe1" param1="CustomIcon" />
    <property name="PlantGrowing.LightLevelGrow" value="0" />
    <property name="PlantGrowing.LightLevelStay" value="0" /> <!-- might not need (default) -->
    <property name="PlantGrowing.FertileLevel" value="0" /> <!-- might not need (default) -->

    <!-- TODO: remove every unnecessary lines beyond this point -->
    <property name="CreativeMode" value="Player" />
    <property name="UnlockedBy" value="perkLivingOffTheLand,plantedAloe1Schematic" />
    <property name="Material" value="Mcorn" />
    <property name="Shape" value="ModelEntity" />
    <property name="Model" value="Entities/Plants/plant_aloe1_Prefab" />
    <property name="PlaceAsRandomRotation" value="true" />
    <property name="PlantGrowing.Next" value="plantedUndergroundAloe2" />
    <property name="Group" value="Food/Cooking,Science" />
    <drop event="Destroy" name="plantedAloe1" count="1" />
  </block>
</append>
```

## Additions in `recipes.xml`
*Existing recipe ingredients for each seed + recipe ingredients for mushroom seed.*

Type | 1 | 2 | 3 | 4 | 5
--- | --- | --- | --- | --- | ---
Aloe Vera | 5 resourceCropAloeLeaf | 5 foodCropMushrooms | 2 resourceClayLump
Blueberry | 5 foodCropBlueberries | 5 foodCropMushrooms | 2 resourceClayLump
Chrysanthemum | 5 resourceCropChrysanthemumPlant | 5 foodCropMushrooms | 2 resourceClayLump
Coffee | 5 resourceCropCoffeeBeans | 5 foodCropMushrooms | 2 resourceClayLump
Corn | 5 foodCropCorn | 5 foodCropMushrooms | 2 resourceClayLump
Cotton | 5 resourceCropCottonPlant | 5 foodCropMushrooms | 2 resourceClayLump
Goldenrod | 5 resourceCropGoldenrodPlant | 5 foodCropMushrooms | 2 resourceClayLump
Hops | 5 resourceCropHopsFlower | 5 foodCropMushrooms | 2 resourceClayLump
Potato | 5 foodCropPotato | 5 foodCropMushrooms | 2 resourceClayLump
Pumpkin | 5 foodCropPumpkin | 5 foodCropMushrooms | 2 resourceClayLump
Super Corn | 5 foodCropGraceCorn | 5 foodCropMushrooms | 2 resourceClayLump
Yucca | 5 foodCropYuccaFruit | 5 foodCropMushrooms | 2 resourceClayLump

**Comment by Shavick** [comment]
I'm here too :D Shavick
